ietf-tools/www

ietf/settings/base.py

* Set `FILE_UPLOAD_PERMISSIONS` to `0o664` on Django site settings. (#111)

Set FILE_UPLOAD_PERMISSIONS settings

---

db_reset.sh

This PR fixes an issue where the public schema won't be recreated during DB sync script runs.

Fix DB sync script not creating public schema

---

ietf/bibliography/templates/bibliography/bibliography.html
ietf/blog/templates/blog/blog_page.html
ietf/blog/templates/includes/blog_filters.html
ietf/blog/templates/includes/blog_sidebar.html
ietf/standard/templates/standard/standard_index_page.html
ietf/standard/templates/standard/standard_page.html
ietf/static_src/css/bs-override.scss
ietf/static_src/css/main.scss
ietf/templates/includes/breadcrumbs.html
ietf/templates/includes/row_siblings_in_section.html
ietf/templates/includes/styles/index.scss
ietf/topics/templates/topics/primary_topic_page.html

Changes made:
- Change background colour from grey to white
- Add 24px bottom padding to breadcrumb and remove heading style
- Increase all headings weight to 600
- Reduce body weight to 300
- Remove Uppercase styling on sidebar heading
- Add border and change bg colour to grey in sidebar
- Divider line (between header and body) constrained to margins (rather than spanning whole page width). 
Springload figma link: https://www.figma.com/file/QdmAlSacAoO23ru613kMhZ/IETF-UI-tweaks?node-id=78%3A19&t=lAmRHoslsYHVp0bU-0
From this:
to this:

Springload changes for #240, #241 & #243

---

ietf/static_src/css/streamfield.scss

Make images in typed tables shrink to fit as per [this comment](https://springload-nz.atlassian.net/browse/IEF-24?focusedCommentId=44563).

fix: images in tables shrink to fit

---

ietf/static_src/css/iab.scss

Fix behaviour seen [here](https://springload.slack.com/archives/C01S53GEP4M/p1687142648571159), now when you click the arrow the submenu stays in place.

fix: Menu jumping on click

---

.github/workflows/ci-run-tests.yml
docker-compose.yml
docker/init-test.sh
ietf/settings/base.py
requirements.txt

build: Use memcached

---

ietf/blog/feeds.py
ietf/blog/tests.py
ietf/home/models.py
ietf/home/templates/home/iab_home_page.html
ietf/home/templates/includes/post_iab.html
ietf/settings/base.py
ietf/urls.py

* feat: Use IETF IAB blog feed on the home page
* feat: Add IAB blog feed
Fixes #317

feat: Use IETF IAB blog feed on the home page

---

docker/Dockerfile
docker/init-dev.sh
docker/init-test.sh
pyproject.toml

This patch adds [pytest-django](https://pytest-django.readthedocs.io/en/latest/index.html), to run the testsuite with pytest, and [pytest-cov](https://github.com/pytest-dev/pytest-cov), to measure coverage.
Refs. https://github.com/ietf-tools/wagtail_website/issues/131

feat: Run tests with pytest and measure coverage

---

.github/workflows/ci-run-tests.yml
.gitignore
docker/init-test.sh

This PR generates an XML coverage report and uploads it to Codecov. It needs the `CODECOV_TOKEN` actions secret to be set on the repository (IIUC it's already there).
Here's a report uploaded from my fork: https://app.codecov.io/github/mgax/ietf-wagtail_website/commit/66b3878f087ba707ab345e4cfb6ca498cdba27cd/tree
Refs. https://github.com/ietf-tools/wagtail_website/pull/339#issuecomment-1798096246
Fixes https://github.com/ietf-tools/wagtail_website/issues/131

feat: Upload coverage reports to Codecov

---

ietf/templates/iab_base.html
ietf/templates_src/base.html

Fixes https://github.com/ietf-tools/wagtail_website/issues/288
Django's [`{% spaceless %}`](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#spaceless) template tag removes whitespace between HTML tags, including adjacent links. This patch removes the _spaceless_ tag from the base templates. It's still used in the `includes/imageblock.html` template, where it's not liable to squash adjacent inline markup: https://github.com/ietf-tools/wagtail_website/blob/v1.10.0/ietf/templates/includes/imageblock.html#L1

fix: Remove spaceless template tag

---

.nvmrc
README.md
docker-compose.yml
docker/database/02_convert_native_dump_to_sql_and_restore.sh
docker/init-dev.sh

- Alow for more flexibility in database dump filenames
- Fix indentation in the README Markdown
- ~Use Django's `runserver` instead of gunicorn~
- Allow changing the port exposed by Docker
- Specify the Node version in `.nvmrc` that matches the frontend Dockerfile

fix: Improve developer experience

---

ietf/blog/templates/blog/blog_page.html
ietf/iesg_statement/templates/iesg_statement/iesg_statement_page.html
ietf/templates/includes/social_share.html

I've fixed a couple of issues, that I've noticed while working on another ticket, and the page http://localhost:8001/about/groups/iesg/statements/interim-meetings-guidance-2023-01-27/ crashed.
- Add missing variables passed into the social sharing sub-template (latent issue surfaced by https://github.com/ietf-tools/wagtail_website/pull/358).
- Remove spaces between social sharing icons (issue introduced in https://github.com/ietf-tools/wagtail_website/pull/347).

fix: Social sharing box for IESG Statement pages

---

docker/Dockerfile

For https://github.com/ietf-tools/wagtail_website/issues/173, we're integrating the [wagtail-ab-testing](https://github.com/wagtail-nest/wagtail-ab-testing)  package, which unfortunately depends on numpy and scipy.
While numpy provides pre-compiled wheels for Alpine on both x86-64 and aarch64, scipy only provides alpine wheels for x86-64. This means people with newer ARM-based Macs (myself included) would have a hard time working on the project, either having to build and run the Docker image using emulation, or we'd have to modify the build process to compile scipy (which is both difficult and very slow).
Switching to Debian means we can use the scipy "manylinux" flavour of wheel, which is available for aarch64 too.

refactor: Switch to a Debian base image

---

ietf/events/models.py

Fixes https://github.com/ietf-tools/wagtail_website/issues/327.
I was able to reproduce the error, and this patch makes it go away. I'm not entirely sure what was causing it. `pk` is an alias for the primary key field, which is `id` for the `EventPage` model, so in any case, the new code is still correct.

fix: crash when previewing Event Listing Page

---

dev/deploy-to-container/cli.js
ietf/settings/production.py

Fixes #374
Production and staging deployments will need setting `CSRF_TRUSTED_ORIGINS` on `local.py`.

fix:  Set CSRF_TRUSTED_ORIGINS

---

ietf/utils/context_processors.py
ietf/utils/models.py

Refs. https://github.com/ietf-tools/wagtail_website/issues/326
I was testing what happens when a page from the megamenu is deleted, something I'd skipped over in the main PR, and found a couple of related issues.
With this change, if a page is deleted, its link becomes empty, and it will be skipped when rendering the menu.
This PR also makes local development slightly easier: in the megamenu, links to pages will be [generated](https://docs.wagtail.org/en/stable/reference/pages/model_reference.html#wagtail.models.Page.get_url) as _local URLs_, so that they point to _localhost_ instead of _www.ietf.org_.
Additionally, after applying the [utils.0009_megamenu](https://github.com/ietf-tools/wagtail_website/blob/main/ietf/utils/migrations/0009_megamenu.py) migration, I suggest running …

fix: Generate local URLs for megamenu and skip empty links

---

ietf/settings/base.py
ietf/utils/apps.py
ietf/utils/signal_handlers.py

Fixes https://github.com/ietf-tools/wagtail_website/issues/361.
- Generate a Cloudflare _API token_ (not API key) with permissions to purge cache: https://docs.wagtail.org/en/stable/reference/contrib/frontendcache.html#cloudflare. Set it as the `CLOUDFLARE_CACHE_PURGE_BEARER_TOKEN` environment variable.
- Retrieve the Zone ID of the Cloudflare zone for www.ietf.org. Set it as the `CLOUDFLARE_CACHE_PURGE_ZONE_ID` environment variable.
- Change the Wagtail site (in the admin, Settings -> Sites) so that its port is 443. This tells Wagtail to generate `https://` URLs. Otherwise, it will try to purge `http://` URLs, which won't work.
- To test that cache purge works, run `curl -s https://www.ietf.org -I | grep cache`. It should print `cf-cache-status: HIT` for a cached page and …

feat: Purge Cloudflare cache

---

docker/init-test.sh

When [the CI checks for missing migrations](https://github.com/ietf-tools/www/blob/d963ff91c2a619f8a12f6d41ddc6e8a03a0aedc4/docker/init-test.sh#L8), it doesn't print any output, so it's difficult to figure out what failed (e.g. [this failure](https://github.com/ietf-tools/www/actions/runs/8423748999/job/23066090470#step:6:275)). With this patch, [the output](https://github.com/ietf-tools/www/actions/runs/8434427323/job/23097626477#step:6:281) is actually helpful.
https://stackoverflow.com/a/77259833/51801

ci: Print missing migrations in CI

---

.github/workflows/codeql-analysis.yml

Fix CodeQL warning in CI by upgrading to ~V2~ V3.
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
This addresses warnings in Actions, like on this [latest run on `main`](https://github.com/ietf-tools/www/actions/runs/8444471453):

chore: Upgrade to CodeQL v3

---

ietf/utils/context_processors.py

From @ghwood:
> I think I have found a bug in the [new main menu structure](https://github.com/ietf-tools/www/issues/326) where the auto-generated elements of a megamenu main menu item do not actually link to the specific pages intended. For example, at https://wwwstaging.ietf.org/ see the links under the “Process” heading such as “Internet standards process”. The manually-linked elements (such as the “Appeals” element under the “Standards process” heading) do work as expected.
This is also fixed in https://github.com/ietf-tools/www/pull/395, but it might be worth merging the fix before that PR, so that the megamenu can be deployed.

fix: Links in megamenu

---

CONTRIBUTING.md

Making it more debug-friendly when testing locally

docs: Enable logging when running postgres container locally

---

ietf/settings/base.py

Assuming we only want to keep up-to-date with long-term support versions of Wagtail, this configures the update warning to ignore non-LTS releases.
---
It's still asking for an upgrade from 5.2.1 to 5.2.4; we should put in place some mechanism to automate dependency updates, at least for security-related updates.

chore: Only offer LTS version upgrades

---

helm/values.yaml

chore: Use prod settings by default in Helm chart

---

docker/gunicorn.py
docker/nginx-sandbox.conf
docker/supervisord-sandbox.conf

Fixes #432 and #433
I can see both Nginx and Gunicorn logs when I run `kubectl logs -f` locally now.
```text
127.0.0.1 - - [23/Apr/2024:04:23:57 +0100] "GET /healthz HTTP/1.0" 200 2 "-" "kube-probe/1.28" "10.244.0.1"
127.0.0.1 - - [23/Apr/2024:04:23:57 +0100] "GET /healthz HTTP/1.0" 200 2 "-" "kube-probe/1.28" "10.244.0.1"
10.244.0.1 - - [23/Apr/2024:03:23:57 +0000] "GET /healthz HTTP/1.1" 200 2 "-" "kube-probe/1.28"
10.244.0.1 - - [23/Apr/2024:03:23:57 +0000] "GET /healthz HTTP/1.1" 200 2 "-" "kube-probe/1.28"
127.0.0.1 - - [23/Apr/2024:04:24:06 +0100] "GET / HTTP/1.0" 200 30624 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" "127.0.0.1"
127.0.0.1 - - [23/Apr/2024:03:24:06 +0000] "GET / HTTP/1.1" 200 5552 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; …
```

chore: Capture Nginx and Gunicorn logs in stdout

---

ietf/blog/models.py

Fix https://github.com/ietf-tools/www/issues/337.
Fix https://github.com/ietf-tools/www/issues/271.
The blog page template depends on its parent page being a `BlogPageIndex`, so it crashes if its parent is anything else.

fix: BlogPage may only be created under BlogIndexPage

---

helm/templates/cronjob.yaml
helm/values.yaml

Fixes \#431.
-   Two cron jobs:
The PR defines two cron jobs, one hourly the other weekly.
<https://docs.wagtail.org/en/stable/reference/management_commands.html>
-   `publish_scheduled`:
> We recommend running this command once an hour.
-   `update_index`:
> It is recommended to run this command once a week
With the current spec, the daily job runs every hour at minute 0, and the weekly job runs on Sunday at 00:30 UTC. Note that the weekly database maintenance window currently occurs on Saturdays UTC, and will no overlap with the weekly cron job.
-   Verifying `helm install` output:
With `tag` set to the latest image tag, `v2.1.10`, `helm install www helm --dry-run` outputs as below.
``` yaml
...
---
apiVersion: batch/v1
kind: CronJob
metadata:
name: "mgmt-hourly"
spec:
schedule: "0 * * …
```

feat: Define cron jobs running mgmt commands in Helm chart

---

helm/templates/cronjob.yaml
helm/values.yaml

refactor: Force same image repository and tag for wagtail and crons

---

ietf/context_processors.py
ietf/templates/includes/footer.html

Fixes #456
Tested on https://ws-social-icons.dev.ietf.org
Google Chrome Lighthouse Accessibility report is happy with social media links.

fix: Add title to social media links (#457)

---

k8s/iabweb/secrets.yaml

chore: Remove trailing /admin/ from WAGTAILADMIN_BASE_URL in secrets

---

.github/workflows/accessibility-test.yml
.github/workflows/ci-run-tests.yml
docker-compose.yml

ci: Run accessibility tests

---

k8s/iabweb/cron.yaml
k8s/iabweb/kustomization.yaml

chore: Add weekly cron job for updating index

---

docker/Dockerfile

Use python:3.12-bookworm instead of python:3.12-slim-bookworm.

chore: Use python:3.12-bookworm

---

.github/workflows/build.yml

ci: remove v prefix from image tags

---

ietf/home/styles/home.scss

At certain screen sizes the homepage paper plane in the footer can appear over the button (in Chrome/Firefox), obscuring clicks, but this makes the paper plane image avoid clicks so that the user can interact with the button.

fix: home page cta container obscuring button click

---

docker/gunicorn.py

Number of worker connections is unset. Default is 1000.
Keep alive time out is unset. Default is 2.
Removed server obfuscation header.
Removed obsolete `X-CLOUDFRONT` setting.
This updates number of workers and threads to match the number of core.

chore: Tweak gunicorn config

---

ietf/search/templates/search/search.html

fix: Return only live pages from search promotions

---

k8s/ietfweb/nginx-default.conf

Try `.html` and `.txt` files if file extension is not provided.

chore(nginx): Try html and txt files for IDs and RFCs
