ietf/static_src/css/streamfield.scss

Reduces table padding from 20px to 10px.  Closes #76 and #85

Reduces table padding

---

ietf/templates/404.html

Remove URL reference from 404 'Did you know' text

---

ietf/settings/base.py
ietf/utils/blocks.py
package.json
requirements.txt
yarn.lock

Add wagtailmarkdown

---

docker/Dockerfile
docker/init-dev.sh
install.md

* Adds additional instructions to getting a local instance up with a data
dump. Fixes #119

Improves install.md instructions

---

ietf/templates/includes/footer.html

Fix: footer vertical padding

---

.circleci/config.yml
docker/Dockerfile
docker/init-test.sh

Enable backend tests on circleci.

Enable backend tests

---

ietf/blog/models.py

Some small changes to prefetch authors for blog posts

Prefetch authors of blog posts

---

ietf/glossary/models.py
ietf/glossary/templates/glossary/glossary_page.html

Single page glossary

---

ietf/settings/base.py
ietf/urls.py

Implements `sitemap.xml`. See #135

Adds sitemap.xml

---

ietf/templates/404.html

fix: Typo in 404 template

---

docker/init-test.sh

test: Check for missing migrations

---

ietf/static_src/css/streamfield.scss
yarn.lock

pr [IEF-25](https://springload-nz.atlassian.net/jira/software/projects/IEF/boards/105?selectedIssue=IEF-25)

remove margin, wideth and add max width

---

ietf/static_src/css/streamfield.scss

175 Improve handling of photo captions
- [IEF-22](https://springload-nz.atlassian.net/jira/software/projects/IEF/boards/105?selectedIssue=IEF-22)

make img caption smaller

---

ietf/templates/404.html

fix: Update 404.html (#244)

---

ietf/home/models.py
ietf/home/templates/home/iab_home_page.html

This pull request improves the filtering of Events, DRYs some of the HomePage code and fixes a couple of links.

feat: Improve event filtering

---

ietf/settings/base.py
ietf/standard/models.py

feat: Restrict IAB & IETF page types to their respective site trees.

feat: Restrict IAB & IETF page types to their respective site trees.

---

ietf/standard/templates/standard/iab_standard_page.html
ietf/static_src/css/iab-colors.scss
ietf/static_src/css/iab.scss
ietf/templates/includes/header_iab.html

Modifications to nav menu and key info / in depth tabs, relevant commit added direct to existing branch.

feat: Front end changes and tweaks

---

ietf/settings/base.py

chore: Use test repository for note well for testing

---

README.md
ietf/settings/docker/base.py

chore: Remove Matomo settings from base settings file

---

ietf/static_src/css/iab.scss
ietf/templates/includes/footer-iab.html

https://springload-nz.atlassian.net/jira/software/projects/IAB/boards/178?selectedIssue=IAB-36

fix: use static url

---

ietf/announcements/templates/announcements/iab_announcement_index_page.html

https://springload-nz.atlassian.net/jira/software/projects/IAB/boards/178?selectedIssue=IAB-37

fix: remove row styling

---

ietf/static_src/css/bs-override.scss
ietf/static_src/css/iab.scss

https://springload-nz.atlassian.net/jira/software/projects/IAB/boards/178?selectedIssue=IAB-38

feat: title h1 size on mobile

---

ietf/templates/iab_base.html

[IAB-42](https://springload-nz.atlassian.net/jira/software/projects/IAB/boards/178?selectedIssue=IAB-42)

fix: remove preceeding slash on url

---

ietf/templates/includes/header_iab.html

[IAB-49](https://springload-nz.atlassian.net/jira/software/projects/IAB/boards/178?selectedIssue=IAB-49)

fix: center burger menu items

---

ietf/announcements/templates/announcements/iab_announcement_index_page.html

[IAB-48](https://springload-nz.atlassian.net/jira/software/projects/IAB/boards/178?selectedIssue=IAB-48)

fix: announcements full width

---

ietf/static_src/css/bs-override.scss

Fix whitespace after paragraphs in content pages. 
Before:
After:

IAB-36 paragraph spacing

---

ietf/static_src/css/iab.scss
ietf/templates/includes/header_iab.html

[IAB-51](https://springload-nz.atlassian.net/jira/software/projects/IAB/boards/178?selectedIssue=IAB-51)
Before:
After:
[IAB-51]: https://springload-nz.atlassian.net/browse/IAB-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix:  menu alignment

---

ietf/static_src/css/iab.scss
ietf/templates/includes/header_iab.html

[IAB-50](https://springload-nz.atlassian.net/jira/software/projects/IAB/boards/178)
Before (left) / After (right):
[IAB-50]: https://springload-nz.atlassian.net/browse/IAB-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: menu text size and duplicate searches

---

.dockerignore
.gitignore
ietf/static_src/css/bs-override.scss
ietf/static_src/css/utilities.scss
ietf/templates/includes/header.html
ietf/templates/includes/styles/header.scss
ietf/templates_src/base.html

- Changes header colors to a light grey style
- Use font Inter
- Add roundness to donate button
- Add subtle shadow to header dropdown menus
Other:
- Fix dockerignore / gitignore to properly support db dumps.

feat: header colors rework + change font to Inter

---

.dockerignore
.gitignore
dev/deploy-to-container/.gitignore
docker/database/.gitignore
ietf/settings/.gitignore

Merge all `.gitignore` files in the repository and update `.dockerignore` to match.

refactor: Clean up ignore files

---

docker-compose.yml
ietf/bibliography/__init__.py
ietf/bibliography/apps.py
ietf/bibliography/urls.py
ietf/blog/tests.py
ietf/settings/docker/__init__.py
ietf/snippets/urls.py
ietf/urls.py
pyproject.toml

- Fix deprecation warnings and system checks during development.
- Configure _pytest_ to treat warnings as errors.

chore: Fix warnings

---

docker/Dockerfile

fix: Copy nginx site config to correct location

---

.github/workflows/helm-checks.yml

 ci: Add helm chart test 

---

.github/workflows/build.yml

ci: Publish helm chart

---

helm/values.yaml

fix: Use latest tag for wagtail service in Helm chart

---

helm/local.py
helm/values.yaml

chore: Make cache key prefix configurable

---

helm/templates/_helpers.tpl
ietf/settings/dev.py

chore: Clean up Celery

---

ietf/templates/includes/header.html

Fix https://github.com/ietf-tools/www/issues/407.

chore: Remove the _Donate_ button

---

helm/values.yaml

chore: Set initial delay for startup probe

---

helm/local.py
helm/values.yaml

ci: Add MAIL_PORT to helm chart

---

ietf/context_processors.py
ietf/templates/includes/footer.html

fix: Add title to social media links

---

ietf/templates/404.html

fix: Update 404.html

---

.github/workflows/accessibility-test.yml
.github/workflows/ci-run-tests.yml
accessibility-tests/index.ts
docker-compose.yml

This change adds a daily GHA that runs accessibility tests on www.ietf.org daily.
Note that www.iab.org is commented out since we need to address a few accessibility issues. See #498.
Fixes #315

ci: Run accessibility test periodically

---

k8s/iabweb/nginx-default.conf
k8s/ietfweb/nginx-default.conf

build: Disable nginx upload file size check

---

ietf/bibliography/templatetags/bibliography.py

fix: avoid trying to use relations that do not exist yet

---

ietf/search/tests.py
ietf/search/views.py

fix: Strip NULL characters in search query

---

requirements/base.txt
requirements/dev.txt
requirements/docker.txt

This has minor updates for Wagtail and Django.

chore(deps): Update Python dependencies

---

k8s/ietfweb/nginx-default.conf

build: Try txt files for minutes

---

requirements/base.txt
requirements/dev.txt

Also update other Python dependencies.

build(deps): Bump up wagtail to 6.3.3

---

docker/Dockerfile

build: Use up-to-date Docker syntax

---

k8s/iabweb/cron.yaml

build: Add rebuild_references_index to weekly cron

---

k8s/ietfweb/cron.yaml
k8s/ietfweb/kustomization.yaml

build: Add weekly cron jobs for ietfweb

---

ietf/search/tests.py
ietf/search/views.py

fix: Limit number of search terms

---

requirements/base.in
requirements/base.txt
requirements/dev.txt

feat: Update to wagtail 7.0.2

---

k8s/iabweb/cron.yaml

* Changes cronjob frequency to hourly from weekly.
* Add `publish_scheduled` command to cronjob command list.

build(iab): Add hourly cron job for document publishing

---

requirements/base.txt
requirements/dev.txt

Also update other Python dependencies.

chore(deps): Bump up wagtail to 7.0.3
